"""add_embedding_column

Revision ID: 842f89b4c7da
Revises: 7eb9dbd489d9
Create Date: 2026-06-04 18:53:56.237773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '842f89b4c7da'
down_revision: Union[str, None] = '7eb9dbd489d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'embedding')
    # ### end Alembic commands ###
